# Generated by Django 5.0.3 on 2024-03-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nobre_equipo', models.CharField(max_length=50, verbose_name='Nombre')),
                ('img_bandera', models.TextField(unique=True, verbose_name='Bandera')),
                ('img_escudo', models.TextField(unique=True, verbose_name='Escudo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'Equipo',
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id_posicion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_posicion', models.CharField(max_length=50, verbose_name='Posicion jugador')),
                ('descripcion_posicion', models.TextField(unique=True, verbose_name='descripcion de la posicion')),
            ],
            options={
                'verbose_name': 'Posicion',
                'verbose_name_plural': 'Posiciones',
                'db_table': 'Posicion',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id_jugador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_jugador', models.CharField(max_length=50, verbose_name='Nombre jugador')),
                ('apellido_jugador', models.TextField(max_length=50, verbose_name='Apellido jugador')),
                ('foto', models.TextField(unique=True, verbose_name='Foto jugador')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('numero_camiseta', models.TextField(max_length=2, verbose_name='Numero de camiseta')),
                ('titular', models.BooleanField(verbose_name='Titular')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.equipo', verbose_name='Equipo')),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.posicion', verbose_name='Posicion')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'Jugador',
            },
        ),
    ]
