# Generated by Django 5.0.3 on 2024-03-07 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, verbose_name='Nombre rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tecnico', models.CharField(max_length=50, verbose_name='Nombre tecnico')),
                ('apellido_tecnico', models.TextField(max_length=50, verbose_name='Apellido tecnico')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('nacionalidad', models.TextField(max_length=30, verbose_name='Nacionalidad')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.equipo', verbose_name='Equipo')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.roles', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Tecnico',
                'verbose_name_plural': 'Tecnicos',
                'db_table': 'Tecnico',
            },
        ),
    ]
