# Generated by Django 5.0.3 on 2024-03-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_roles_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='apellido_jugador',
            field=models.CharField(max_length=50, verbose_name='Apellido jugador'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='numero_camiseta',
            field=models.CharField(max_length=2, verbose_name='Numero de camiseta'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='apellido_tecnico',
            field=models.CharField(max_length=50, verbose_name='Apellido tecnico'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='nacionalidad',
            field=models.CharField(max_length=30, verbose_name='Nacionalidad'),
        ),
    ]
